spring.application.name=discovery-server
server.port=8761
server.address=0.0.0.0

# Le serveur Eureka ne doit PAS s’enregistrer lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Actuator pour healthcheck Docker
management.endpoints.web.exposure.include=health,info,env,metrics
management.endpoint.health.show-details=always

# (optionnel) si tu veux forcer le context-path
# server.servlet.context-path=
# eureka.server.context-path=