spring.application.name=notifications-service
server.port=8085

# -------------------------
# DATABASE MONGODB
# -------------------------
spring.data.mongodb.uri=mongodb://mongodb:27017/eventhub_notifications

# -------------------------
# RABBITMQ
# -------------------------
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# -------------------------
# EUREKA
# -------------------------
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
# -------------------------
# SECURITY (JWT)
# -------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/eventhub
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=realm_access.roles
spring.security.oauth2.resourceserver.jwt.authority-prefix=ROLE_
