spring.application.name=notifications-service
server.port=8085

# -------------------------
# DATABASE MONGODB
# -------------------------
spring.data.mongodb.uri=mongodb://mongodb:27017/eventhub_notifications

# -------------------------
# RABBITMQ
# -------------------------
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# -------------------------
# EUREKA
# -------------------------
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
# -------------------------
# SECURITY (JWT)
# -------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/eventhub
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=realm_access.roles
spring.security.oauth2.resourceserver.jwt.authority-prefix=ROLE_

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mansour.takwa@gmail.com
spring.mail.password=pfwi mqex ixwn ryol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
