spring.application.name=users-service
server.port=8080

# -------------------------
# DATABASE POSTGRES
# -------------------------
spring.datasource.url=jdbc:postgresql://postgres:5432/eventhub-users
spring.datasource.username=eventhub_user
spring.datasource.password=eventhub123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------
# EUREKA
# -------------------------
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true


# Actuator pour endpoints utiles
management.endpoints.web.exposure.include=health,info,env,conditions,beans,configprops,refresh
management.endpoint.health.show-details=always

# Debug ordre des propertySources et config client
logging.level.org.springframework.cloud=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.cloud.config.client=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.org.springframework.web.reactive=DEBUG

# Optionnel : activer le mode debug global de Spring Boot (affiche ConditionEvaluationReport)
# (ou passer --debug en ligne de commande)
spring.main.log-startup-info=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/eventhub
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/eventhub/protocol/openid-connect/certs