server:
  port: 8088

spring:
  application:
    name: api-gateway

  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/eventhub
          authorities-claim-name: realm_access.roles
          authority-prefix: ROLE_

  cloud:
    gateway:
      routes:

        # 🔥 Routes de test des rôles
        - id: admin-test
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/admin/test

        - id: user-test
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/user/test

        # 🔥 Routes normales
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: events-service
          uri: lb://EVENTS-SERVICE
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1

        - id: reservations-service
          uri: lb://RESERVATIONS-SERVICE
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
