# port et nom d'appli (déjà présents)
server.port=8888
spring.application.name=config-server

# backend git (déjà présent)
spring.cloud.config.server.git.uri=file:///G:/AWD/eventhub/config-repo
spring.cloud.config.server.git.default-label=main

# exposer les endpoints actuator nécessaires
management.endpoints.web.exposure.include=health,mappings,info,env,metrics
management.endpoint.health.show-details=always
