# port et nom d'appli (déjà présents)
server.port=8888
spring.application.name=config-server

# backend git (déjà présent)
spring.cloud.config.server.native.search-locations=file:./config-repo
spring.profiles.active=native

# exposer les endpoints actuator nécessaires
management.endpoints.web.exposure.include=health,mappings,info,env,metrics
management.endpoint.health.show-details=always
